name: Docker

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2 # This step logs in to the Docker Hub using the secrets
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # This step sets up Buildx, a tool that allows building multi-arch images
      - name: Build and push
        uses: docker/build-push-action@v3 # This step performs the actual build and push to Docker Hub
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-server:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          # Cache the image layers
          cache-from: type=gha
          cache-to: type=gha,mode=max
